version: '3.7'

services:
  postgres:
    image: postgres:12.2-alpine
    restart: always
    ports:
      - 5458:5432
    volumes:
      - postgres-data:/var/lib/postgresql/data
    environment:
    # Safest credentials :3
      - POSTGRES_USER=db
      - POSTGRES_PASSWORD=db
      - POSTGRES_DB=db
  

volumes:
  postgres-data: