version: '3.7'

services:
  postgres:
    image: postgres:12.2-alpine
    ports:
      - 5458:5432
    volumes:
      - postgres-data:/var/lib/postgresql/data
    environment:
    # Safest credentials :3
      - POSTGRES_USER=db
      - POSTGRES_PASSWORD=db
      - POSTGRES_DB=db

  clickhouse:
    image: yandex/clickhouse-server
    ports:
      - "8123:8123"
    volumes:
      - clickhouse-data:/var/lib/clickhouse
    ulimits:
      nproc: 65535
      nofile:
        soft: 262144
        hard: 262144

  nats:
    image: nats:latest
    ports:
      - "4222:4222"
      - "8222:8222"

  redis:
    image: redis:latest
    ports:
      - "6379:6379"

volumes:
  postgres-data:
  clickhouse-data: